name: hikers_dash
description: A web dashboard to contol hiking activities
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.4.4
  firebase_core: ^2.7.1
  url_launcher: ^6.1.10
  email_validator: ^2.1.17
  provider: ^6.0.5
  firebase_auth: ^4.3.0
  flutter_spinkit: ^5.1.0
  uuid: ^3.0.7
  responsive_builder: ^0.7.0
  flutter_svg: ^2.0.7
  mpesa_flutter_plugin: ^1.6.1
  feature_folder_cli: ^0.3.0
  sidebarx: ^0.16.1
  collection: ^1.17.1
  font_awesome_flutter: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
    
  assets:
    - assets/images/logo.svg
    - assets/images/download.jpeg
    - assets/images/254.jpeg
      
